package probe

// This file uses bpf2go to compile the eBPF C code and generate Go bindings
// at `go generate` time. The generated code provides type-safe access to
// BPF programs and maps.
//
// How bpf2go works:
//   1. At `go generate` time, it runs clang to compile bpf/probes.c → BPF bytecode
//   2. It embeds the compiled bytecode into a Go source file (probes_bpfel.go)
//   3. It generates Go structs for all BPF maps and programs
//   4. At runtime, we just call LoadProbes() — no external .o files needed!
//
// The generated file contains:
//   - probesObjects: struct with all BPF programs and maps
//   - probesSpecs: BPF object specification (for customization before loading)
//   - loadProbes(): load all BPF objects into the kernel

//go:generate go run github.com/cilium/ebpf/cmd/bpf2go -cc clang -cflags "-O2 -g -Wall -Wno-missing-declarations -target bpf -D__TARGET_ARCH_x86 -I../../bpf/headers" -target amd64 probes ../../bpf/probes.c

import (
	"fmt"
	"log/slog"

	"github.com/cilium/ebpf"
	"github.com/cilium/ebpf/link"
	"github.com/cilium/ebpf/ringbuf"
)

// Probe manages the lifecycle of all eBPF programs and maps.
//
// It handles:
//   - Loading compiled eBPF bytecode into the kernel
//   - Attaching programs to kernel hooks (kprobes, kretprobes, tracepoints)
//   - Creating a ring buffer reader for event consumption
//   - Cleaning up everything on shutdown (detach, close maps)
//
// Usage:
//
//	p, err := probe.New(probe.DefaultConfig())
//	if err != nil { ... }
//	defer p.Close()
//	reader := p.NewReader()
type Probe struct {
	objs   probesObjects // Generated by bpf2go — holds all BPF programs and maps
	links  []link.Link   // Kernel attachments (kprobes, tracepoints) — closed on shutdown
	config Config
	logger *slog.Logger
}

// New loads the eBPF programs into the kernel and attaches them to hooks.
//
// This function:
//   1. Loads the compiled BPF bytecode (embedded in the binary by bpf2go)
//   2. Attaches kprobes/kretprobes to tcp_v4_connect
//   3. Attaches kretprobe to inet_csk_accept
//   4. Attaches kprobe to tcp_close
//   5. Attaches tracepoint to tcp:tcp_retransmit_skb
//
// Requires CAP_BPF (or root). If any step fails, all resources are cleaned up.
func New(cfg Config, logger *slog.Logger) (*Probe, error) {
	if logger == nil {
		logger = slog.Default()
	}

	p := &Probe{
		config: cfg,
		logger: logger,
	}

	// Load BPF objects (programs + maps) into the kernel.
	// The spec allows us to customize map sizes before loading.
	spec, err := loadProbes()
	if err != nil {
		return nil, fmt.Errorf("loading BPF spec: %w", err)
	}

	// Override ring buffer size from config (zero hardcoding compliance)
	if m, ok := spec.Maps["events"]; ok {
		m.MaxEntries = uint32(cfg.RingBufferSize)
		logger.Info("ring buffer size configured", "bytes", cfg.RingBufferSize)
	}

	// Load all programs and maps into the kernel
	if err := spec.LoadAndAssign(&p.objs, &ebpf.CollectionOptions{}); err != nil {
		return nil, fmt.Errorf("loading BPF objects into kernel: %w", err)
	}
	logger.Info("eBPF programs loaded into kernel")

	// Attach all probes to their kernel hooks.
	// If any attachment fails, we clean up everything and return an error.
	if err := p.attachProbes(); err != nil {
		p.Close() // Clean up anything that was attached before the failure
		return nil, fmt.Errorf("attaching probes: %w", err)
	}

	logger.Info("all eBPF probes attached",
		"probes", len(p.links),
	)

	return p, nil
}

// attachProbes attaches each BPF program to its kernel hook.
func (p *Probe) attachProbes() error {
	var l link.Link
	var err error

	// --- tcp_v4_connect: kprobe (entry) ---
	l, err = link.Kprobe("tcp_v4_connect", p.objs.TcpV4ConnectEntry, nil)
	if err != nil {
		return fmt.Errorf("attaching kprobe/tcp_v4_connect: %w", err)
	}
	p.links = append(p.links, l)
	p.logger.Debug("attached kprobe", "function", "tcp_v4_connect")

	// --- tcp_v4_connect: kretprobe (exit) ---
	l, err = link.Kretprobe("tcp_v4_connect", p.objs.TcpV4ConnectExit, nil)
	if err != nil {
		return fmt.Errorf("attaching kretprobe/tcp_v4_connect: %w", err)
	}
	p.links = append(p.links, l)
	p.logger.Debug("attached kretprobe", "function", "tcp_v4_connect")

	// --- inet_csk_accept: kretprobe ---
	l, err = link.Kretprobe("inet_csk_accept", p.objs.InetCskAcceptExit, nil)
	if err != nil {
		return fmt.Errorf("attaching kretprobe/inet_csk_accept: %w", err)
	}
	p.links = append(p.links, l)
	p.logger.Debug("attached kretprobe", "function", "inet_csk_accept")

	// --- tcp_close: kprobe ---
	l, err = link.Kprobe("tcp_close", p.objs.TcpCloseEntry, nil)
	if err != nil {
		return fmt.Errorf("attaching kprobe/tcp_close: %w", err)
	}
	p.links = append(p.links, l)
	p.logger.Debug("attached kprobe", "function", "tcp_close")

	// --- tcp:tcp_retransmit_skb: tracepoint ---
	l, err = link.Tracepoint("tcp", "tcp_retransmit_skb", p.objs.HandleTcpRetransmit, nil)
	if err != nil {
		return fmt.Errorf("attaching tracepoint/tcp/tcp_retransmit_skb: %w", err)
	}
	p.links = append(p.links, l)
	p.logger.Debug("attached tracepoint", "group", "tcp", "name", "tcp_retransmit_skb")

	return nil
}

// NewReader creates a ring buffer reader for consuming events.
//
// The caller is responsible for closing the returned reader.
// Events are read by calling reader.Read() in a loop.
func (p *Probe) NewReader() (*ringbuf.Reader, error) {
	rd, err := ringbuf.NewReader(p.objs.Events)
	if err != nil {
		return nil, fmt.Errorf("creating ring buffer reader: %w", err)
	}
	return rd, nil
}

// Close detaches all probes and releases all BPF resources.
//
// This MUST be called on shutdown to cleanly remove probes from the kernel.
// If probes aren't detached, they continue running (wasting CPU) until
// the process exits (at which point the kernel garbage-collects them).
func (p *Probe) Close() {
	// Close all attachments (kprobes, tracepoints)
	// We iterate in reverse order so we detach in LIFO order
	for i := len(p.links) - 1; i >= 0; i-- {
		if err := p.links[i].Close(); err != nil {
			p.logger.Warn("failed to close link", "index", i, "error", err)
		}
	}
	p.links = nil

	// Close all BPF objects (programs + maps)
	if err := p.objs.Close(); err != nil {
		p.logger.Warn("failed to close BPF objects", "error", err)
	}

	p.logger.Info("eBPF probes detached and cleaned up")
}
