// Code generated by bpf2go; DO NOT EDIT.
//go:build 386 || amd64

package probe

import (
	"bytes"
	_ "embed"
	"fmt"
	"io"

	"github.com/cilium/ebpf"
)

// Names of all BPF objects in the ELF.
//
// Used for safe lookups in a Collection or CollectionSpec.
const (
	probesMapEvents               = "events"
	probesMapInflightConnects     = "inflight_connects"
	probesProgHandleTcpRetransmit = "handle_tcp_retransmit"
	probesProgInetCskAcceptExit   = "inet_csk_accept_exit"
	probesProgTcpCloseEntry       = "tcp_close_entry"
	probesProgTcpV4ConnectEntry   = "tcp_v4_connect_entry"
	probesProgTcpV4ConnectExit    = "tcp_v4_connect_exit"
)

// loadProbes returns the embedded CollectionSpec for probes.
func loadProbes() (*ebpf.CollectionSpec, error) {
	reader := bytes.NewReader(_ProbesBytes)
	spec, err := ebpf.LoadCollectionSpecFromReader(reader)
	if err != nil {
		return nil, fmt.Errorf("can't load probes: %w", err)
	}

	return spec, err
}

// loadProbesObjects loads probes and converts it into a struct.
//
// The following types are suitable as obj argument:
//
//	*probesObjects
//	*probesPrograms
//	*probesMaps
//
// See ebpf.CollectionSpec.LoadAndAssign documentation for details.
func loadProbesObjects(obj any, opts *ebpf.CollectionOptions) error {
	spec, err := loadProbes()
	if err != nil {
		return err
	}

	return spec.LoadAndAssign(obj, opts)
}

// probesSpecs contains maps and programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type probesSpecs struct {
	probesProgramSpecs
	probesMapSpecs
	probesVariableSpecs
}

// probesProgramSpecs contains programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type probesProgramSpecs struct {
	HandleTcpRetransmit *ebpf.ProgramSpec `ebpf:"handle_tcp_retransmit"`
	InetCskAcceptExit   *ebpf.ProgramSpec `ebpf:"inet_csk_accept_exit"`
	TcpCloseEntry       *ebpf.ProgramSpec `ebpf:"tcp_close_entry"`
	TcpV4ConnectEntry   *ebpf.ProgramSpec `ebpf:"tcp_v4_connect_entry"`
	TcpV4ConnectExit    *ebpf.ProgramSpec `ebpf:"tcp_v4_connect_exit"`
}

// probesMapSpecs contains maps before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type probesMapSpecs struct {
	Events           *ebpf.MapSpec `ebpf:"events"`
	InflightConnects *ebpf.MapSpec `ebpf:"inflight_connects"`
}

// probesVariableSpecs contains global variables before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type probesVariableSpecs struct {
}

// probesObjects contains all objects after they have been loaded into the kernel.
//
// It can be passed to loadProbesObjects or ebpf.CollectionSpec.LoadAndAssign.
type probesObjects struct {
	probesPrograms
	probesMaps
	probesVariables
}

func (o *probesObjects) Close() error {
	return _ProbesClose(
		&o.probesPrograms,
		&o.probesMaps,
	)
}

// probesMaps contains all maps after they have been loaded into the kernel.
//
// It can be passed to loadProbesObjects or ebpf.CollectionSpec.LoadAndAssign.
type probesMaps struct {
	Events           *ebpf.Map `ebpf:"events"`
	InflightConnects *ebpf.Map `ebpf:"inflight_connects"`
}

func (m *probesMaps) Close() error {
	return _ProbesClose(
		m.Events,
		m.InflightConnects,
	)
}

// probesVariables contains all global variables after they have been loaded into the kernel.
//
// It can be passed to loadProbesObjects or ebpf.CollectionSpec.LoadAndAssign.
type probesVariables struct {
}

// probesPrograms contains all programs after they have been loaded into the kernel.
//
// It can be passed to loadProbesObjects or ebpf.CollectionSpec.LoadAndAssign.
type probesPrograms struct {
	HandleTcpRetransmit *ebpf.Program `ebpf:"handle_tcp_retransmit"`
	InetCskAcceptExit   *ebpf.Program `ebpf:"inet_csk_accept_exit"`
	TcpCloseEntry       *ebpf.Program `ebpf:"tcp_close_entry"`
	TcpV4ConnectEntry   *ebpf.Program `ebpf:"tcp_v4_connect_entry"`
	TcpV4ConnectExit    *ebpf.Program `ebpf:"tcp_v4_connect_exit"`
}

func (p *probesPrograms) Close() error {
	return _ProbesClose(
		p.HandleTcpRetransmit,
		p.InetCskAcceptExit,
		p.TcpCloseEntry,
		p.TcpV4ConnectEntry,
		p.TcpV4ConnectExit,
	)
}

func _ProbesClose(closers ...io.Closer) error {
	for _, closer := range closers {
		if err := closer.Close(); err != nil {
			return err
		}
	}
	return nil
}

// Do not access this directly.
//
//go:embed probes_x86_bpfel.o
var _ProbesBytes []byte
