apiVersion: v1
kind: Namespace
metadata:
  name: cascadeshield-test
---
# Service 1: Payments
apiVersion: v1
kind: Service
metadata:
  name: payments
  namespace: cascadeshield-test
spec:
  selector:
    app: payments
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: payments
  namespace: cascadeshield-test
spec:
  replicas: 1
  selector:
    matchLabels:
      app: payments
  template:
    metadata:
      labels:
        app: payments
    spec:
      containers:
        - name: nginx
          image: nginx:alpine
          ports:
            - containerPort: 80
---
# Service 2: Orders (calls Payments)
apiVersion: v1
kind: Service
metadata:
  name: orders
  namespace: cascadeshield-test
spec:
  selector:
    app: orders
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: orders
  namespace: cascadeshield-test
spec:
  replicas: 1
  selector:
    matchLabels:
      app: orders
  template:
    metadata:
      labels:
        app: orders
    spec:
      containers:
        - name: nginx
          image: nginx:alpine
          ports:
            - containerPort: 80
        - name: traffic-generator
          image: curlimages/curl:latest
          command: ["/bin/sh", "-c"]
          args:
            - while true; do curl -s http://payments.cascadeshield-test.svc.cluster.local > /dev/null; sleep 2; done
---
# Service 3: Frontend (calls Orders)
apiVersion: v1
kind: Service
metadata:
  name: frontend
  namespace: cascadeshield-test
spec:
  selector:
    app: frontend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: cascadeshield-test
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - name: nginx
          image: nginx:alpine
          ports:
            - containerPort: 80
        - name: traffic-generator
          image: curlimages/curl:latest
          command: ["/bin/sh", "-c"]
          args:
            - while true; do curl -s http://orders.cascadeshield-test.svc.cluster.local > /dev/null; sleep 2; done
